version: '3.8'
services:
  fp-database:
    image: postgres:latest
    container_name: fp-database
    environment:
      POSTGRES_USER: puzzle
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: puzzle
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
